### ISSUE TITLE
discussion mysql_add

### ISSUE THREAD

**Issue by zergless** [redbrickCmt/admin-scripts#2]
Pretty straight forward adds a user to the mysql DB with a username, password and database. Then emails said information to them
usage ./mysql_add 
Follow the instructions I believe 

https://github.com/redbrick/admin-scripts/blob/master/mysql_add

**Comment by d-fens** [comment]
Keep this, it's always worked, and the permissions aspect are very important.

I also had this fixed in the UCC netsoc as well based on our script.

https://github.com/UCCNetworkingSociety/NetsocAdmin/commit/5f208e4f1dc87339e9d713a48f922daf3f6447a8

**Comment by butlerx** [comment]
keeping script see #4
